[project]
name = "tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "bibtexparser>=1.4.3",
    "requests>=2.32.3",
    "streamlit>=1.41.1",
]
